uploads = []
generated = []

[[outputs]]
id = "16CT_sFxvwdbldtXIyrs_"
uri = "file://Hemalink-blood-bank.tar.gz"
type = "unspecified"
title = "Hemalink Blood Bank - Project Files"

[[outputs]]
id = "RqQ1WNkN7j36jzEFPisQG"
uri = "file://Hemalink_Report_Package.tar.gz"
type = "unspecified"
title = "Hemalink Blood Bank - Project Report + Screenshots"

[[outputs]]
id = "jThNxqTa6gZNbrsJiWBqq"
uri = "file://Hemalink_Complete_Package.tar.gz"
type = "unspecified"
title = "Hemalink Blood Bank - Full Code"
